path: /mnt/e/Projects/FindByColor/models/oid/data
train: images/train 
val: images/val
test: images/test

nc: 349
names:
  0: Tortoise
  1: Magpie
  2: Sea turtle
  3: Football
  4: Ambulance
  5: Toy
  6: Apple
  7: Beer
  8: Bird
  9: Traffic light
  10: Croissant
  11: Cucumber
  12: Radish
  13: Towel
  14: Skull
  15: Washing machine
  16: Glove
  17: Belt
  18: Ball (Object)
  19: Backpack
  20: Surfboard
  21: Chopsticks
  22: Boot
  23: Hot dog
  24: Shorts
  25: Bus
  26: Boy
  27: Screwdriver
  28: Bicycle wheel
  29: Barge
  30: Laptop
  31: Miniskirt
  32: Drill (Tool)
  33: Dress
  34: Bear
  35: Waffle
  36: Pancake
  37: Brown bear
  38: Woodpecker
  39: Blue jay
  40: Pretzel
  41: Bagel
  42: Teapot
  43: Person
  44: Swimwear
  45: Bat (Animal)
  46: Starfish
  47: Popcorn
  48: Burrito
  49: Balloon
  50: Wrench
  51: Vehicle registration plate
  52: Toaster
  53: Flashlight
  54: Limousine
  55: Carnivore
  56: Scissors
  57: Computer keyboard
  58: Printer
  59: Traffic sign
  60: Shirt
  61: Cheese
  62: Sock
  63: Fire hydrant
  64: Tie
  65: Suitcase
  66: Muffin
  67: Snowmobile
  68: Clock
  69: Camel
  70: Cattle
  71: Cello
  72: Jet ski
  73: Suit
  74: Cat
  75: Bronze sculpture
  76: Juice
  77: Computer mouse
  78: Cookie
  79: Coin
  80: Calculator
  81: Cocktail
  82: Box
  83: Stapler
  84: Christmas tree
  85: Cowboy hat
  86: Studio couch
  87: Drink
  88: Zucchini
  89: Ladle
  90: Human mouth
  91: Dice
  92: Oven
  93: Couch
  94: Cricket ball
  95: Winter melon
  96: Spatula
  97: Whiteboard
  98: Hat
  99: Shower
  100: Eraser
  101: Fedora
  102: Guacamole
  103: Dagger
  104: Scarf
  105: Dolphin
  106: Sombrero
  107: Mug
  108: Tap
  109: Harbor seal
  110: Human body
  111: Roller skates
  112: Coffee cup
  113: Stop sign
  114: Volleyball (Ball)
  115: Vase
  116: Slow cooker
  117: Coffee (drink)
  118: Paper towel
  119: Sun hat
  120: Flying disc
  121: Skirt
  122: Barrel
  123: Kite
  124: Tart
  125: Fox
  126: Flag
  127: Guitar
  128: Pillow
  129: Grape
  130: Human ear
  131: Power plugs and sockets
  132: Panda
  133: Giraffe
  134: Woman
  135: Door handle
  136: Rhinoceros
  137: Goldfish
  138: Goat
  139: Baseball bat
  140: Baseball glove
  141: Mixing bowl
  142: Light switch
  143: Horse
  144: Hammer
  145: Sofa bed
  146: Adhesive tape
  147: Saucer
  148: Harpsichord
  149: Heater
  150: Harmonica
  151: Hamster
  152: Kettle
  153: Drinking straw
  154: Hair dryer
  155: Food processor
  156: Punching bag
  157: Common fig
  158: Cocktail shaker
  159: Jaguar (Animal)
  160: Golf ball
  161: Alarm clock
  162: Filing cabinet
  163: Artichoke
  164: Motorcycle
  165: Kangaroo
  166: Koala
  167: Knife
  168: Bottle
  169: Bottle opener
  170: Lynx
  171: Lighthouse
  172: Dumbbell
  173: Bowl
  174: Lizard
  175: Billiard table
  176: Mouse
  177: Swim cap
  178: Frying pan
  179: Missile
  180: Bust
  181: Man
  182: Milk
  183: Mobile phone
  184: Mushroom
  185: Pitcher (Container)
  186: Pencil case
  187: Briefcase
  188: Kitchen knife
  189: Table tennis racket
  190: Nail (Construction)
  191: Tennis ball
  192: Plastic bag
  193: Chest of drawers
  194: Ostrich
  195: Piano
  196: Girl
  197: Potato
  198: Hair spray
  199: Penguin
  200: Pumpkin
  201: Pear
  202: Polar bear
  203: Pizza
  204: Pig
  205: Digital clock
  206: Skateboard
  207: Reptile
  208: Lipstick
  209: Raven
  210: High heels
  211: Red panda
  212: Rose
  213: Rabbit
  214: Sculpture
  215: Saxophone
  216: Submarine sandwich
  217: Sword
  218: Picture frame
  219: Loveseat
  220: Squirrel
  221: Segway
  222: Snake
  223: Skyscraper
  224: Sheep
  225: Tea
  226: Tank
  227: Torch
  228: Tiger
  229: Strawberry
  230: Tomato
  231: Train
  232: Cooking spray
  233: Trousers
  234: Truck
  235: Measuring cup
  236: Handbag
  237: Paper cutter
  238: Wine
  239: Wheel
  240: Wok
  241: Whale
  242: Zebra
  243: Jug
  244: Pizza cutter
  245: Monkey
  246: Lion
  247: Bread
  248: Platter
  249: Chicken
  250: Eagle
  251: Owl
  252: Duck
  253: Turtle
  254: Hippopotamus
  255: Crocodile
  256: Toilet
  257: Toilet paper
  258: Clothing
  259: Lemon (plant)
  260: Frog
  261: Banana
  262: Rocket
  263: Oyster
  264: Chisel
  265: Tablet computer
  266: Waste container
  267: Dog
  268: Book
  269: Elephant
  270: Shark
  271: Candle
  272: Leopard
  273: Axe
  274: Hand dryer
  275: Soap dispenser
  276: Flower
  277: Canary
  278: Cheetah
  279: Hamburger
  280: Fish
  281: Garden Asparagus
  282: Hedgehog
  283: Fixed-wing aircraft
  284: Spoon
  285: Otter
  286: Bull
  287: Bomb
  288: Orange (fruit)
  289: Beaker
  290: Goose
  291: Mule
  292: Swan
  293: Peach
  294: Seat belt
  295: Raccoon
  296: Camera
  297: Squash (Plant)
  298: Racket
  299: Diaper
  300: Falcon
  301: Cabbage
  302: Carrot
  303: Mango
  304: Jeans
  305: Flowerpot
  306: Envelope
  307: Cake
  308: Common sunflower
  309: Microwave oven
  310: Sea lion
  311: Watch
  312: Parrot
  313: Handgun
  314: Sparrow
  315: Van
  316: Corded phone
  317: Tennis racket
  318: Dog bed
  319: Facial tissue holder
  320: Pressure cooker
  321: Ruler
  322: Luggage and bags
  323: Broccoli
  324: Pastry
  325: Grapefruit
  326: Band-aid
  327: Bell pepper
  328: Turkey
  329: Pomegranate
  330: Doughnut
  331: Pen
  332: Car
  333: Aircraft
  334: Skunk
  335: Teddy bear
  336: Watermelon
  337: Cantaloupe
  338: Flute
  339: Balance beam
  340: Sandwich
  341: Binoculars
  342: Ipod
  343: Alpaca
  344: Taxi
  345: Canoe
  346: Remote control
  347: Rugby ball
  348: Armadillo